MTES-MCT/monitor-ui

src/elements/Fieldset.tsx, src/fields/CoordinatesInput/DDCoordinatesInput.tsx, src/fields/CoordinatesInput/DMDCoordinatesInput.tsx, src/fields/CoordinatesInput/DMSCoordinatesInput.tsx, src/fields/CoordinatesInput/index.tsx, src/formiks/FormikCoordinatesInput.tsx, src/hooks/useFieldUndefineEffect.ts, src/index.ts, src/types.ts, stories/fields/CoordinatesInput.stories.tsx, stories/formiks/FormikCoordinatesInput.stories.tsx
BREAKING CHANGE: CoordinatesInput onChange can now send undefined params
BREAKING CHANGE: label is now mandatory in CoordinatesInput
None
https://637e01cf5934a2ae881ccc9d-snerbxtmcv.chromatic.com/
=> feat(fields)!: add disabled, error & label props to CoordinatesInput

package.json, yarn.lock
Because Cypress v12 is not in peer deps of https://github.com/ivangabriele/cypress-plugin-snapshots in last tag
https://637e01cf5934a2ae881ccc9d-iwzonhnhem.chromatic.com/
=> fix(deps): downgrade cypress version

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/merge_dependabot_pull_request.yml
=> ci(github): limit workflow run event to e2e in Dependabot auto-merge workflow

.github/workflows/merge_dependabot_pull_request.yml
=> ci(github): limit Dependabot auto-merge workflow to Dependanbot branches

.github/workflows/merge_dependabot_pull_request.yml
=> ci(github): limit Dependabot auto-merge workflow to Dependanbot branches (bis)

src/fields/Checkbox.tsx, src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/index.tsx, src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, src/fields/MultiSelect.tsx, src/fields/MultiZoneEditor/index.tsx, src/fields/Search.tsx, src/fields/Select.tsx, src/fields/Textarea.tsx, src/formiks/FormikEffect.tsx
BREAKING CHANGE: Fields `style` & `className` props are now passed to the container.
None
https://637e01cf5934a2ae881ccc9d-mbtlfvwmgx.chromatic.com/
=> fix(fields)!: move style prop passing to container level

src/components/Dropdown/Item.tsx, src/utils/__tests__/getOptionsFromLabelledEnum.test.ts, src/utils/getOptionsFromLabelledEnum.ts, stories/components/Dropdown.stories.tsx
BREAKING CHANGE:
- add mustSort prop with default value to false for sorted or not the options
https://637e01cf5934a2ae881ccc9d-fcakgtchtw.chromatic.com/
=> feat(utils)!: add prop to getOptionsFromLabelledEnum function for sorted or not the options

src/assets/stylesheets/rsuite-override.css, src/fields/MultiRadio.tsx, stories/fields/MultiRadio.stories.tsx, stories/fields/TextInput.stories.tsx
Customize multiRadio style for readOnly mode
- MTES-MCT/monitorenv#827
https://637e01cf5934a2ae881ccc9d-rsimvjgski.chromatic.com/
=> feat(fields): add isReadOnly prop on multiRadio component and add custom style for plaintext

src/components/Dropdown/Item.tsx, src/components/Dropdown/index.tsx, src/components/SideMenu/Button.tsx, src/components/SingleTag.tsx, src/elements/Button.tsx, src/elements/IconButton.tsx, src/fields/DatePicker/CalendarPicker.tsx, src/fields/DateRangePicker/DateInput.tsx, src/fields/DateRangePicker/RangeCalendarPicker.tsx, src/fields/DateRangePicker/RangedTimePicker.tsx, src/fields/DateRangePicker/TimeInput.tsx, src/fields/MultiSelect.tsx, src/fields/NumberInput.tsx, src/fields/Select.tsx, src/fields/TextInput.tsx, src/fields/Textarea.tsx, src/tables/SimpleTable.tsx, src/theme.ts, stories/Colors.stories.tsx
BREAKING CHANGE:
Accentuation colors are no longer objects with key accentuation but just string with this pattern `colorAccentuationNumber`. Exemple: `blueYonder[25]` becomes `blueYonder25`
https://637e01cf5934a2ae881ccc9d-jkauedvyjb.chromatic.com/
=> feat(theme)!: add new color and update accentuation colors

src/assets/stylesheets/rsuite-override.css
J'avais un probleme au niveau du display des Radio buttons qui s'affichent très mal dans RNav. Ca s'affiche mieux dans Monitor (je sais pas pourquoi) mais si vous regardez bien précisément, il y a un décalage de 1px aussi chez Monitor.
J'ai retravaillé les tailles et l'alignement (c'est dur de center align dans un object qui a une taille impaire)
avant:
après:
https://637e01cf5934a2ae881ccc9d-ltoxkuhhpe.chromatic.com/
=> fix(Multiradio): rework sizing and centering

src/fields/CoordinatesInput/DDCoordinatesInput.tsx, src/fields/CoordinatesInput/DMDCoordinatesInput.tsx, src/fields/CoordinatesInput/DMSCoordinatesInput.tsx, src/fields/CoordinatesInput/index.tsx
Le Coordinate Input était assez cassé en light mode, il héritait d'un Fieldset en mode light qui ajoute un padding non nécessaire.
Ce padding est très utile pour les MultiRadio et MultiCheckbox mais pas pour les autres composants.
Je me suis inspiré d'autres composants (DatePicker par ex) qui déplace la prop `isLight` du Fieldset vers l'Input.
avant :
apres :
https://637e01cf5934a2ae881ccc9d-hwiannwjnf.chromatic.com/
=> fix(CoordinatesInput): fix light mode

src/fields/MultiSelect.tsx
Petit souci au niveau du MultiSelect lorsque les labels sont vraiment longs (typiquement pour les Natinfs).
Le problème n'apparait qu'en mode virtualized (j'ai 1000 items dans la liste). C'est correctement truncate en mode normal ceci dit.
avant :
après :
On remarquera que le text n'est pas truncate mais plutôt que le Select devient scrollable horizontalement. C'est un peu que l'on peut rediscuter.
https://637e01cf5934a2ae881ccc9d-cxuafdiufy.chromatic.com/
=> fix(MultiSelect): fix for long labels in virtualized mode

src/fields/Checkbox.tsx, stories/fields/Checkbox.stories.tsx
Lors des tests RapportNav, Clémence s'est aperçu que le mode readOnly sur les Checkbox ne respectait pas les designs. Elle le voulait plus passif, sans hover, comme les Input ou Radio.
avant:
https://github.com/MTES-MCT/monitor-ui/assets/4593884/caf858d4-76a1-4bb4-b84f-8f1232f852d1
après:
https://github.com/MTES-MCT/monitor-ui/assets/4593884/2d7021ff-52d9-49be-beb7-7d0d1290f8e7
https://637e01cf5934a2ae881ccc9d-mvsqhvores.chromatic.com/
=> style(Checkbox) - override default readOnly mode

.eslintrc.cjs, src/components/Message.tsx, src/elements/IconButton.tsx, src/elements/Tag/index.tsx, src/fields/CheckPicker.tsx, src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/index.tsx, src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, src/fields/MultiSelect.tsx, src/fields/NumberInput.tsx, src/fields/Search.tsx, src/fields/Select.tsx, src/fields/TextInput.tsx, src/fields/Textarea.tsx, src/symbols/ExclamationPoint.tsx, src/tables/DataTable/Td.tsx, src/tables/DataTable/Th.tsx, src/tables/DataTable/index.tsx, src/utils/coordinates.ts, src/utils/getUtcizedDayjs.ts, stories/tables/SimpleTable.stories.tsx, stories/tables/TableWithSelectableRows.stories.tsx
- Je n'ai réservé le nullish coalescing operator que pour les cas de valeurs par défaut qui ne soient pas booléennes.
- Pour les booléens j'ai préféré,m'assurer de caster toutes les valeurs des `if` via `!!`.
None
https://637e01cf5934a2ae881ccc9d-ccjnoxhquj.chromatic.com/
=> lint(eslint): enforce nullish coalescing

src/entities/Administration.ts, src/entities/ControlUnit/types.ts, src/entities/ControlUnit/utils.ts, src/entities/Station.ts, src/index.ts
None
https://637e01cf5934a2ae881ccc9d-ybzqnzyijm.chromatic.com/
=> feat(entities): add getControlUnitResourceCategoryFromType() util

src/cypress/commands/fill/fillTextInput.ts
https://637e01cf5934a2ae881ccc9d-badvvyyent.chromatic.com/
=> fix(cypress): widen input type for fill() on TextInput

src/fields/MultiCascader/index.tsx, src/fields/MultiSelect.tsx, src/fields/Search.tsx, stories/fields/DateRangePicker.stories.tsx, stories/fields/MultiCascader.stories.tsx, tsconfig.json
BREAKING CHANGE:
- `baseContainer` prop has been removed in `MultiCascader`.
- `baseContainer` prop has been removed in `MultiSelect`.
- `baseContainer` prop has been removed in `Search`.
https://637e01cf5934a2ae881ccc9d-moabrfmquj.chromatic.com/
=> ci(github)!: fix typo in E2E Test job

src/fields/Textarea.tsx
Un truc qu'on a remarqué avec Clémence : le textarea peut dépasser son parent lors du resize et on aimerait bloquer ce comportement.
https://github.com/MTES-MCT/monitor-ui/assets/4593884/c4b788db-149e-4acf-adde-6445990e9bc1
https://637e01cf5934a2ae881ccc9d-pnymxcivak.chromatic.com/
=> fix(fields): prevent resizing from exceeding 100% parent width

src/utils/__tests__/getMaybeBooleanFromRichBoolean.test.ts, src/utils/getMaybeBooleanFromRichBoolean.ts
https://637e01cf5934a2ae881ccc9d-nappaswoub.chromatic.com/
=> feat(utils): include undefined value in getMaybeBooleanFromRichBoolean()

src/fields/CoordinatesInput/index.tsx
L'astérisque rouge ne se montrait pas alors qu'il y avaut la prop isRequired
https://637e01cf5934a2ae881ccc9d-qdeqztjvss.chromatic.com/
=> fix(fields): CoordinatesInput now displays the * when isRequired

src/symbols/ExclamationPoint.tsx, stories/elements/Tag.stories.tsx, stories/symbols/ExclamationPoint.stories.tsx
Petit souci sur le point d'exclamation quand il était intégré à un Tag (16px au lieu de 20px)
https://637e01cf5934a2ae881ccc9d-hywiyvrmka.chromatic.com/
=> feat(symbols): rework ExclamationPoint to resize dynamically

src/components/Banner/index.tsx
Affichage du `LinkButton` en rouge dans le cas où la bannière est de type `ERROR`
https://637e01cf5934a2ae881ccc9d-iodhhkllhn.chromatic.com/
=> fix(component): display hide text in red when level isError in banner component

src/fields/Textarea.tsx
Le Textarea peut être réduit en horizontal par l'utilisateur, ce qui est à éviter selon Clémence.
https://637e01cf5934a2ae881ccc9d-olcwcvvdqu.chromatic.com/
=> fix(fields): prevent textarea from being horizontally reduced

src/components/Message/index.tsx
https://637e01cf5934a2ae881ccc9d-jjeyaytwzy.chromatic.com/
=> fix(components): remove typo in Message class name

.eslintrc.cjs, config/jest.config.js, src/fields/Checkbox.tsx, src/tables/SimpleTable/CellLoader.tsx, src/tables/SimpleTable/Td.tsx, src/tables/SimpleTable/index.tsx, src/tables/TableWithSelectableRows/RowCheckbox.tsx, src/tables/TableWithSelectableRows/index.tsx, stories/fields/CheckPicker/WithCustomSearch.stories.tsx, stories/fields/MultiCascader/WithThreeColumns.stories.tsx, stories/fields/MultiSelect/WithCustomSearch.stories.tsx, stories/fields/Select/WithCustomSearch.stories.tsx, stories/tables/SimpleTable/WithLoader.stories.tsx, stories/tables/TableWithSelectableRows.stories.tsx, tsconfig.json
- Remove `isChecked` prop in `TableWithSelectableRows.RowCheckbox`, replaced by native `checked` prop.
- Remove `isIndeterminate` prop in `TableWithSelectableRows.RowCheckbox`, replaced by original Rsuite `indeterminate` prop.
- Remove `$isHighlighted` prop in `TableWithSelectableRows.Td`, replaced by the same prop on `TableWithSelectableRows.BodyTr`.
- In order to work properly with `RowCheckbox`, `TableWithSelectableRows` now requires `<Table $withRowCheckbox />`.
- Following the `SimpleTable` & `TableWithSelectableRows` margins/heights normalization, including a few hacks,
it may break some UI widths & heights.
- Please check `TableWithSelectableRows.stories.tsx` to see a full example on how to use/update it.
- As shown in the story, be careful **NOT** to wrap the checkbox table header …
=> feat(tables)!: add $isLoading prop to SimpleTable.Td, normalize all tables margins/heights & checkboxes

src/components/NewWindow.tsx
- MTES-MCT/monitorfish#2843
https://637e01cf5934a2ae881ccc9d-gsiyrybwzy.chromatic.com/
=> fix(components): ignore external domain stylesheets in NewWindow styles copying

src/elements/Label.tsx, src/fields/CheckPicker.tsx, src/fields/MultiCascader/index.tsx, src/fields/MultiSelect.tsx, src/fields/NumberInput.tsx, src/fields/PhoneInput.tsx, src/fields/Search.tsx, src/fields/Select.tsx, src/fields/TextInput.tsx, src/fields/Textarea.tsx, src/fields/Toggle/index.tsx, stories/elements/Label.stories.tsx
https://637e01cf5934a2ae881ccc9d-lfvbrxllcn.chromatic.com/
=> [A11Y]: Modification de la propriété isHidden pour rendre le label accessible

src/elements/IconButton.tsx, stories/elements/IconButton.stories.tsx
- https://github.com/MTES-MCT/monitorfish/issues/3427
https://637e01cf5934a2ae881ccc9d-pfbyygqvhf.chromatic.com/
=> feat(elements): add spotlighted number to icon button

package.json, yarn.lock
BREAKING CHANGE: @sentry/react must be upgraded to v8.
- MTES-MCT/monitorfish#3493
https://637e01cf5934a2ae881ccc9d-hklrffzyav.chromatic.com/
=> build(peer-deps)!: upgrade @sentry/react to v8

package.json, yarn.lock
BREAKING CHANGE:
- @tanstack/react-table is added as a peer dependency set to v^8.0.0.
- @tanstack/react-virtual is added as a peer dependency set to v^3.0.0.
None.
https://637e01cf5934a2ae881ccc9d-xytrxnmuhs.chromatic.com/
=> build(dev-deps)!: stabilize @tanstack/react-virtual from beta to 3.8.4

src/utils/__tests__/getOptionsFromLabelledEnum.test.ts, src/utils/getOptionsFromLabelledEnum.ts
- MTES-MCT/monitorfish#3398
https://637e01cf5934a2ae881ccc9d-jgmijmpbzq.chromatic.com/
=> fix(utils): sort by French natural order in getOptionsFromLabelledEnum()

src/elements/Button.tsx, src/elements/Label.tsx, src/fields/CheckPicker.tsx, src/fields/MultiCascader/index.tsx, src/fields/MultiSelect.tsx, src/fields/NumberInput.tsx, src/fields/PhoneInput.tsx, src/fields/Search.tsx, src/fields/Select.tsx, src/fields/TextInput.tsx, src/fields/Textarea.tsx, src/fields/Toggle/index.tsx, stories/elements/Label.stories.tsx
- `disabled` is renamed `$isDisabled` in `Label` props.
- `hasError` is renamed `$hasError` in `Label` props.
- `isHidden` is renamed `$isHidden` in `Label` props.
- MTES-MCT/monitorfish#3633
https://637e01cf5934a2ae881ccc9d-ddqzdqrqzh.chromatic.com/
=> fix(elements): add missing prefixes to styled components props

e2e/release/sample/package-lock.json, e2e/release/sample/package.json, src/fields/Select.tsx, stories/fields/Select/WithCustomSearch.stories.tsx
- MTES-MCT/monitorfish#3211
- https://github.com/bvaughn/react-window/issues/227
https://637e01cf5934a2ae881ccc9d-cgnhnmvxpo.chromatic.com/
=> fix(fields): fix pointer-events in Select

src/cypress/commands/clickButton.ts
None
https://637e01cf5934a2ae881ccc9d-olsypmmuie.chromatic.com/
=> fix(cypress): pass missing option to retry in clickButton()

src/components/Banner/index.tsx, src/elements/Link.tsx, src/elements/LinkButton.tsx
- `children` prop is now a required prop in `<LinkButton />`.
- `<p>` wrapper has been removed from `<LinkButton />` string  `children`.
None.
https://637e01cf5934a2ae881ccc9d-rtluwehwwf.chromatic.com/
=> fix(elements)!: remove p tag & enforce string children in LinkButton

e2e/base/fields/DateRangePicker.spec.tsx, src/fields/DateRangePicker/index.tsx
- cf. https://github.com/MTES-MCT/monitorfish/issues/3726
- Ajout de la props `hasFullDayDefaultValue`
Avec le clavier :
[Screencast from 17-10-2024 15:43:05.webm](https://github.com/user-attachments/assets/5f6c5435-3d24-428a-ab59-282a6bf4ade6)
Avec le picker :
[Screencast from 17-10-2024 15:43:56.webm](https://github.com/user-attachments/assets/bd2acb3b-70c0-4a58-ba08-ec5c28d3c6b0)
https://637e01cf5934a2ae881ccc9d-ipxyfwvmmj.chromatic.com/
=> feat(fields): add hasFullDayDefaultValue to date range picker

src/hooks/useNewWindow/context.ts
- MTES-MCT/monitorfish#3777
https://637e01cf5934a2ae881ccc9d-qbgtpwknzw.chromatic.com/
=> fix(hooks): add window definition guard to NewWindowContext

src/tables/SimpleTable/index.tsx, stories/tables/SimpleTable.stories.tsx, stories/tables/TableWithSelectableRows.stories.tsx
https://637e01cf5934a2ae881ccc9d-lrvvrilmij.chromatic.com/
=> fix(tables): fix scroll in virtualize tables

package.json, src/entities/ControlUnit/types.ts, yarn.lock
- MTES-MCT/monitorenv#2073
https://637e01cf5934a2ae881ccc9d-lkcebryrxa.chromatic.com/
=> feat(entities): add ULAMControlUnitIds

src/components/Tooltip/Tooltip.tsx, stories/components/Tooltip.stories.tsx
- MTES-MCT/monitorfish#4037
https://637e01cf5934a2ae881ccc9d-pulxxkqtow.chromatic.com/
=> feat(components): add Tooltip
