.gitattributes
None
https://637e01cf5934a2ae881ccc9d-bjgvhlerfb.chromatic.com/
=> ci(git): remove useless gitmodules and gitattributes files

README.md
None
https://637e01cf5934a2ae881ccc9d-gkrdmuifnx.chromatic.com/
=> docs(readme): add NPM badge

src/formiks/FormikDateRangePicker.tsx, src/index.ts, stories/formiks/FormikDateRangePicker.stories.tsx, tsconfig.json
None
https://637e01cf5934a2ae881ccc9d-yclqtowvmv.chromatic.com/
=> feat(formiks): add FormikDateRangePicker

scripts/build/copyPublicFiles.sh
=> feat(assets): add rsuite-override stylesheet

src/fields/Checkbox.tsx, src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/index.tsx, src/fields/Select.tsx, src/formiks/FormikSelect.tsx, src/index.ts, stories/fields/Checkbox.stories.tsx, stories/fields/DatePicker.stories.tsx, stories/fields/DateRangePicker.stories.tsx, stories/fields/Select.stories.tsx, stories/formiks/FormikDatePicker.stories.tsx, stories/formiks/FormikDateRangePicker.stories.tsx, stories/formiks/FormikSelect.stories.tsx
=> feat(fields): add Checkbox

tsconfig.dist.single.json
=> refactor(rollup): remove useless tsconfig.dist.single.json file

src/formiks/FormikCheckbox.tsx, src/formiks/FormikSelect.tsx, src/formiks/FormikTextInput.tsx, src/index.ts, stories/formiks/FormikTextInput.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-nhklldheqg.chromatic.com/
=> feat(formiks): add FormikTextInput

src/formiks/FormikTextarea.tsx, src/index.ts, stories/formiks/FormikCheckbox.stories.tsx, stories/formiks/FormikDatePicker.stories.tsx, stories/formiks/FormikDateRangePicker.stories.tsx, stories/formiks/FormikMultiSelect.stories.tsx, stories/formiks/FormikSelect.stories.tsx, stories/formiks/FormikTextarea.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-xocicoukix.chromatic.com/
=> feat(formiks): add FormikTextarea

src/fields/MultiSelect.tsx, stories/fields/MultiSelect.stories.tsx, stories/fields/Select.stories.tsx, stories/formiks/FormikMultiSelect.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-tywoaomijn.chromatic.com/
=> fix(fields): add fixedWidth prop to MultiSelect

src/assets/rsuite-override.css
=> style(assets): update Rsuite override stylesheet

.storybook/preview.jsx, src/elements/Label.tsx, src/elements/Legend.tsx, src/fields/Checkbox.tsx, src/fields/MultiSelect.tsx, src/fields/Select.tsx, src/fields/TextInput.tsx, src/fields/Textarea.tsx, stories/elements/Label.stories.tsx, stories/fields/MultiSelect.stories.tsx, stories/fields/Select.stories.tsx, stories/fields/TextInput.stories.tsx, stories/fields/Textarea.stories.tsx, stories/formiks/FormikMultiSelect.stories.tsx, stories/formiks/FormikSelect.stories.tsx, stories/formiks/FormikTextInput.stories.tsx, stories/formiks/FormikTextarea.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-rxqukfxmwp.chromatic.com/
=> feat(fields): add missing labels

src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx
=> fix(fields): make optional labels mandatory

.github/dependabot.yml, .github/renovate.json
=> ci(dependabot): migrate from renovate

.github/dependabot.yml
=> ci(dependabot): remove redundant scope

.github/dependabot.yml
=> ci(dependabot): set schedule interval from daily to weekly

src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx
=> fix(fields): add missing keys in multi fields

src/elements/Legend.tsx
None
https://637e01cf5934a2ae881ccc9d-olqcqedjyo.chromatic.com/
=> style(elements): remove Legend padding

src/fields/Checkbox.tsx, src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx
None
https://637e01cf5934a2ae881ccc9d-ohbsiorvdr.chromatic.com/
=> style(fields): normalize Checkbox, MultiCheckbox and MultiRadio spacing

.releaserc
None
https://637e01cf5934a2ae881ccc9d-zzmuepsqih.chromatic.com/
=> ci(semantic-release): set release notes generator preset to angular

rollup.config.js
=> fix(build): set right font paths

rollup.config.js, scripts/build/copyPublicFiles.sh
=> fix(build): set include fonts as inline data

src/assets/stylesheets/rsuite-override.css, src/components/Dropdown/Item.tsx, src/components/Dropdown/index.tsx, src/elements/IconBox.tsx, src/index.ts, stories/components/Dropdown.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-jjumccnvjd.chromatic.com/
=> feat(components): add Dropdown

src/elements/Button.tsx
None
https://637e01cf5934a2ae881ccc9d-htotznpldd.chromatic.com/
=> style(elements): fix tertiary Button color

src/elements/Fieldset.tsx, src/fields/MultiSelect.tsx, src/fields/Select.tsx, src/fields/TextInput.tsx, src/fields/Textarea.tsx, stories/elements/Fieldset.stories.tsx, stories/fields/MultiSelect.stories.tsx, stories/fields/Select.stories.tsx, stories/fields/TextInput.stories.tsx, stories/fields/Textarea.stories.tsx
=> feat(fields): add isLight prop in MultiSelect, Select, Textarea, TextInput

src/elements/IconButton.tsx
None
https://637e01cf5934a2ae881ccc9d-ykvfzehjry.chromatic.com/
=> feat(elements): add iconSize prop to IconButton

src/components/Dropdown/Item.tsx, src/components/Dropdown/index.tsx, src/fields/DatePicker/CalendarPicker.tsx, src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, src/fields/MultiSelect.tsx, src/fields/Select.tsx, src/fields/TextInput.tsx, src/fields/Textarea.tsx
=> fix(fields): prefix styled custom props with $

.storybook/preview.tsx, src/components/Dropdown/Item.tsx, src/components/Dropdown/index.tsx, src/elements/Fieldset.tsx, src/elements/Label.tsx, src/fields/DatePicker/CalendarPicker.tsx, src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/DateInput.tsx, src/fields/DateRangePicker/NumberInput.tsx, src/fields/DateRangePicker/RangeCalendarPicker.tsx, src/fields/DateRangePicker/RangedTimePicker.tsx, src/fields/DateRangePicker/TimeInput.tsx, src/fields/DateRangePicker/index.tsx, src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, stories/Icon.stories.tsx, stories/_components/Output.tsx, stories/_components/Showcase/Table.tsx, stories/_components/Showcase/index.tsx, stories/components/Dropdown.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-jercknemxp.chromatic.com/
=> style: convert all rem to px except for Icon size prop

CONTRIBUTING.md, src/fields/MultiSelect.tsx, stories/fields/MultiSelect.stories.tsx, stories/formiks/FormikMultiSelect.stories.tsx
BREAKING CHANGE: Both MultiSelect and FormikMultiSelect `fixedWidth` prop are now in px instead of rem.
None
=> feat(fields)!: convert MultiSelect fixedWidth prop from rem to px

src/formiks/FormikAutoComplete.tsx, src/formiks/FormikCheckbox.tsx, src/formiks/FormikDatePicker.tsx, src/formiks/FormikDateRangePicker.tsx, src/formiks/FormikMultiCheckbox.tsx, src/formiks/FormikMultiRadio.tsx, src/formiks/FormikMultiSelect.tsx, src/formiks/FormikSelect.tsx, src/formiks/FormikTextInput.tsx, src/formiks/FormikTextarea.tsx
None
https://637e01cf5934a2ae881ccc9d-zzgmdprjij.chromatic.com/
=> fix(formiks): remove set undefined on destruction

src/elements/TagGroup.tsx
=> fix(elements): use gap instead of margin in TagGroup

scripts/build/generatePackageJson.js
None
https://637e01cf5934a2ae881ccc9d-svfurcdozc.chromatic.com/
=> fix(types): update type definitions path

package.json
=> fix(build): remove useless npm engine version

src/OnlyFontGlobalStyle.ts, src/index.ts
None
https://637e01cf5934a2ae881ccc9d-egijeoxxon.chromatic.com/
=> feat: add OnlyFontGlobalStyle for legacy integration

src/fields/DateRangePicker/RangeCalendarPicker.tsx
- Resolve MTES-MCT/monitorfish#1380
https://637e01cf5934a2ae881ccc9d-yvouyuuzhx.chromatic.com/
=> fix(fields): force width for DateRangePicker calendar container

.github/PULL_REQUEST_TEMPLATE.md, src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/TimeInput.tsx, src/fields/DateRangePicker/index.tsx, src/hooks/useClickOutside.ts
- MTES-MCT/monitorfish#1657
https://637e01cf5934a2ae881ccc9d-enqgthmddq.chromatic.com/
=> fix(fields): handle detached click outside for time in DatePicker & DateRangePicker

.github/PULL_REQUEST_TEMPLATE.md, src/elements/Button.tsx
=> fix(elements): set Button icon size in px instead of rem

.storybook/components/Output.tsx, src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/index.tsx, src/formiks/FormikDatePicker.tsx, src/formiks/FormikDateRangePicker.tsx, src/index.ts, src/types.ts, src/utils/__tests__/getLocalizedDayjs.test.ts, src/utils/getLocalizedDayjs.ts, stories/fields/DatePicker.stories.tsx, stories/fields/DateRangePicker.stories.tsx, stories/formiks/FormikDatePicker.stories.tsx, stories/formiks/FormikDateRangePicker.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-aymoqrengi.chromatic.com/
=> feat(fields): handle both Date & string dates in DatePicker & DateRangePicker

README.md
None
https://637e01cf5934a2ae881ccc9d-xuyoaijtyv.chromatic.com/
=> docs(readme): update CI status badge

src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/index.tsx, src/utils/__tests__/getLocalizedDayjs.test.ts, src/utils/getLocalizedDayjs.ts
=> fix(fields): fix string date wrong default value offset in DatePicker & DateRangePicker

.storybook/utils/noop.ts, src/fields/DateRangePicker/RangeCalendarPicker.tsx, src/fields/DateRangePicker/index.tsx, src/fields/MultiSelect.tsx, src/fields/Select.tsx, src/utils/noop.ts, stories/formiks/AutoComplete/WithOptions.stories.tsx, stories/formiks/AutoComplete/WithQuery.stories.tsx, stories/formiks/FormikCheckbox.stories.tsx, stories/formiks/FormikDatePicker.stories.tsx, stories/formiks/FormikDateRangePicker.stories.tsx, stories/formiks/FormikEffect.stories.tsx, stories/formiks/FormikMultiCheckbox.stories.tsx, stories/formiks/FormikMultiRadio.stories.tsx, stories/formiks/FormikMultiSelect.stories.tsx, stories/formiks/FormikNumberInput.stories.tsx, stories/formiks/FormikSelect.stories.tsx, stories/formiks/FormikTextInput.stories.tsx, stories/formiks/FormikTextarea.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-ozrbqqncvm.chromatic.com/
=> fix(fields): fix multiple issues

src/fields/MultiSelect.tsx
=> fix(fields): set MutliSelect initial isOpen to false

.storybook/components/Output.tsx, src/components/Dropdown/Item.tsx, src/components/Dropdown/index.tsx
=> fix(components): use px instead of rem for Dropdown icon size

src/elements/Fieldset.tsx, src/fields/MultiSelect.tsx, src/fields/MultiZoneEditor/index.tsx
None
https://637e01cf5934a2ae881ccc9d-xqlnghkwno.chromatic.com/
=> fix(fields): fix MultiSelect placeholder alignment

src/fields/MultiSelect.tsx, src/fields/Select.tsx, stories/fields/Select.stories.tsx
=> fix(fields): fix searchable Select toggling behavior

src/index.ts
- dayjs()
- getLocalizedDayjs()
- getUtcizedDayjs()
- noop()
- stopMouseEventPropagation()
None
https://637e01cf5934a2ae881ccc9d-zsurvskoke.chromatic.com/
=> feat(utils): expose multiple utils

src/formiks/FormikAutoComplete.tsx, src/formiks/FormikCheckbox.tsx, src/formiks/FormikDatePicker.tsx, src/formiks/FormikDateRangePicker.tsx, src/formiks/FormikMultiCheckbox.tsx, src/formiks/FormikMultiRadio.tsx, src/formiks/FormikMultiSelect.tsx, src/formiks/FormikNumberInput.tsx, src/formiks/FormikSelect.tsx, src/formiks/FormikTextInput.tsx, src/formiks/FormikTextarea.tsx
None
https://637e01cf5934a2ae881ccc9d-ohhapnihjh.chromatic.com/
=> feat(formiks): set value to undefined on destroy

src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx
None
https://637e01cf5934a2ae881ccc9d-rwabzryibm.chromatic.com/
=> fix(fields): skip MultiCheckbox render on onChange prop change

src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, src/fields/MultiSelect.tsx, src/fields/Select.tsx
… MultiSelect & Select
None
https://637e01cf5934a2ae881ccc9d-filavuszgt.chromatic.com/
=> feat(fields): make option value generic in MultiCheckbox, MultiRadio, MultiSelect & Select

src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, src/fields/MultiSelect.tsx, src/fields/Select.tsx
=> fix(fields): add missing Option component type generic

src/formiks/FormikMultiCheckbox.tsx, src/formiks/FormikMultiRadio.tsx, src/formiks/FormikMultiSelect.tsx, src/formiks/FormikSelect.tsx
None
https://637e01cf5934a2ae881ccc9d-lxkwwxfjzi.chromatic.com/
=> fix(fields): add missing Option component type generic (bis)

src/components/SingleTag.tsx, src/index.ts, stories/components/SingleTag.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-metlyiucxy.chromatic.com/
=> feat(components): add SingleTag

src/elements/FieldError.tsx, stories/formiks/FormikTextarea.stories.tsx
=> fix(fields): enforce error margins

src/formiks/FormikCheckbox.tsx
None
https://637e01cf5934a2ae881ccc9d-axvbwpsrgq.chromatic.com/
=> fix(formiks): initialize FormikCheckbox form value on mount

src/fields/Select.tsx
+ fix css for close button
https://637e01cf5934a2ae881ccc9d-rxfhbinrqv.chromatic.com/
=> fix(fields): add css selector for toggle event

.storybook/constants.ts, src/fields/MultiSelect.tsx, src/fields/Select.tsx, stories/fields/MultiSelect.stories.tsx, stories/fields/Select.stories.tsx
=> feat(fields): add ellipsis for long options in MultiSelect & Select

src/index.ts
None
https://637e01cf5934a2ae881ccc9d-jlgcvuxdtj.chromatic.com/
=> feat(hooks): expose useKey()

src/index.ts
None
https://637e01cf5934a2ae881ccc9d-yipnqgmddb.chromatic.com/
=> feat(hooks): expose usePrevious()

src/elements/Button.tsx
=> feat(elements): add ellipsis to long Button labels

src/elements/Button.tsx
None
https://637e01cf5934a2ae881ccc9d-aouxodnnjl.chromatic.com/
=> fix(elements): center Button horizontally

src/fields/CoordinatesInput/DDCoordinatesInput.tsx, src/fields/CoordinatesInput/DMDCoordinatesInput.tsx, src/fields/CoordinatesInput/DMSCoordinatesInput.tsx, src/fields/CoordinatesInput/index.tsx
https://637e01cf5934a2ae881ccc9d-gacqxdmkxs.chromatic.com/
=> feat(fieds): Update coordinates input style

src/fields/CoordinatesInput/index.tsx
https://637e01cf5934a2ae881ccc9d-osdvbhqupp.chromatic.com/
=> style(fields): add border to coordinates input

src/formiks/FormikMultiSelect.tsx
value is not updated when changed outside of formikMultiSelect component
https://637e01cf5934a2ae881ccc9d-flrrqdeyeg.chromatic.com/
=> fix(formiks): remove useMemo on fieldValue

.storybook/utils.ts, src/elements/Tag/index.tsx, stories/elements/Tag.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-tbdclzcelv.chromatic.com/
=> feat(elements): add bulletColor prop to Tag

src/constants.ts, src/elements/Tag/constants.ts, src/elements/Tag/index.tsx, src/fields/CoordinatesInput/DMDCoordinatesInput.tsx, src/fields/CoordinatesInput/DMSCoordinatesInput.tsx, src/fields/CoordinatesInput/constants.ts, src/fields/CoordinatesInput/index.tsx, src/index.ts, src/utils/__tests__/coordinates.test.ts, src/utils/coordinates.ts, stories/elements/Tag.stories.tsx
=> fix(elements): expose TagBullet enum

src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/DateInput.tsx, src/fields/DateRangePicker/TimeInput.tsx, src/fields/DateRangePicker/index.tsx, src/fields/DateRangePicker/utils.ts
=> fix(fields): use baseContainer document for active elements in DatePicker & DateRangePicker

src/elements/Fieldset.tsx, src/elements/Legend.tsx, src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, src/fields/MultiSelect.tsx, src/fields/NumberInput.tsx, src/fields/TextInput.tsx
https://637e01cf5934a2ae881ccc9d-kjxadyzbfj.chromatic.com/
=> feat(css): css for errors

.eslintrc.js, package.json, src/elements/Field.tsx, yarn.lock
None
https://637e01cf5934a2ae881ccc9d-snzoyiweis.chromatic.com/
=> feat(elements): add classname .Field to Field

src/fields/MultiSelect.tsx
None
https://637e01cf5934a2ae881ccc9d-tuskbreyui.chromatic.com/
=> fix(fields): fix multiple style issues in MultiSelect

src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, src/fields/MultiSelect.tsx, src/fields/Search.tsx, src/fields/Select.tsx, src/formiks/FormikMultiCheckbox.tsx, src/formiks/FormikMultiRadio.tsx, src/formiks/FormikMultiSelect.tsx, src/formiks/FormikSearch.tsx, src/formiks/FormikSelect.tsx, src/index.ts, src/types.ts, src/utils/getRsuiteDataFromOptions.ts, src/utils/toggleInCollection.ts
None
https://637e01cf5934a2ae881ccc9d-rykttrryvm.chromatic.com/
=> fix(fields): add boolean to generic Option type

.eslintrc.js, CONTRIBUTING.md, e2e/base/formiks/FormikSelect.spec.tsx, src/cypress/.eslintrc.js, src/cypress/commands/fill/pickMultiSelectOptions.ts, src/cypress/commands/fill/pickSelectOption.ts, src/elements/Legend.tsx, src/fields/CoordinatesInput/DDCoordinatesInput.tsx, src/fields/CoordinatesInput/DMDCoordinatesInput.tsx, src/fields/CoordinatesInput/DMSCoordinatesInput.tsx, src/fields/CoordinatesInput/index.tsx, src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/DateInput.tsx, src/fields/DateRangePicker/TimeInput.tsx, src/fields/DateRangePicker/index.tsx, src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, src/fields/MultiSelect.tsx, src/fields/MultiZoneEditor/index.tsx, src/fields/Select.tsx, src/hooks/useFieldControl.ts, src/hooks/useFieldUndefineEffect.ts, src/hooks/useForceUpdate.ts, src/hooks/useKey.ts, src/utils/getRsuiteDataFromOptions.ts, src/utils/getRsuiteValueFromOptionValue.ts, stories/fields/MultiSelect.stories.tsx, stories/fields/Select.stories.tsx, stories/formiks/FormikMultiSelect.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-xkdauxojbg.chromatic.com/
=> fix(fields): handle value prop change in Select & MultiSelect

e2e/base/fields/MultiSelect.spec.tsx, src/fields/MultiSelect.tsx, stories/fields/MultiSelect.stories.tsx, stories/tests/multi_select_with_number_options.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-sfwwqnwnhn.chromatic.com/
=> fix(fields): handle value change in MultiSelect

src/fields/MultiZoneEditor/index.tsx
https://637e01cf5934a2ae881ccc9d-dqrotxhuji.chromatic.com/
=> Add isAddButtonDisabled

.commitlintrc, .github/workflows/check.yml, src/fields/DatePicker/CalendarPicker.tsx, src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/DateInput.tsx, src/fields/DateRangePicker/index.tsx, src/fields/DateRangePicker/utils.ts, stories/fields/DatePicker.stories.tsx
- MTES-MCT/monitorenv#290
https://637e01cf5934a2ae881ccc9d-rsxlmtslug.chromatic.com/
=> feat(fields): add isEndDate prop to DatePicker

src/utils/customDayjs.ts
None
https://637e01cf5934a2ae881ccc9d-cdfqilxmmz.chromatic.com/
=> feat(utils): include more plugins in customDayjs()

src/index.ts
None
https://637e01cf5934a2ae881ccc9d-cklcfllgtz.chromatic.com/
=> fix(utils): include Dayjs plugins typings in customDayjs()

scripts/build/generatePackageJson.js, src/cypress/index.ts
None
https://637e01cf5934a2ae881ccc9d-nbaxmjlbqb.chromatic.com/
=> fix(cypress): export index file instead of directory

src/fields/MultiCheckbox.tsx, stories/fields/MultiCheckbox.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-kggtuozrks.chromatic.com/
=> fix(fields): update value in MultiCheckbox on value prop change

stories/fields/NumberInput.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-mclcqxngkm.chromatic.com/
=> docs(storybook): replace defaultValue by value in NumberInput story

src/fields/Checkbox.tsx, src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, stories/fields/MultiRadio.stories.tsx, stories/fields/NumberInput.stories.tsx, stories/fields/TextInput.stories.tsx, stories/fields/Textarea.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-rrpsmaurnt.chromatic.com/
=> fix(fields): update value in MultiRadio on value prop change

e2e/base/formiks/FormikDatePicker.spec.tsx, e2e/base/formiks/FormikDateRangePicker.spec.tsx, src/fields/DatePicker/CalendarPicker.tsx, src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/DateInput.tsx, src/fields/DateRangePicker/NumberInput.tsx, src/fields/DateRangePicker/RangeCalendarPicker.tsx, src/fields/DateRangePicker/TimeInput.tsx, src/fields/DateRangePicker/index.tsx, src/formiks/FormikDatePicker.tsx, src/formiks/FormikDateRangePicker.tsx, src/hooks/useFieldControl.ts
None
https://637e01cf5934a2ae881ccc9d-eywwwzyupd.chromatic.com/
=> fix(fields): update value in DatePicker & DateRangePicker on defaultValue change

.github/workflows/merge_dependabot_pull_request.yml, .github/workflows/merge_release_pull_request.yml
None
https://637e01cf5934a2ae881ccc9d-fdoekgmvfd.chromatic.com/
=> ci(github): fix GITHUB_TOKEN in merge workflows

.github/workflows/merge_dependabot_pull_request.yml, .github/workflows/merge_release_pull_request.yml, .github/workflows/preview.yml
None
https://637e01cf5934a2ae881ccc9d-tofxvyokww.chromatic.com/
=> ci(github): fix GITHUB_TOKEN in merge workflows (bis)

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/merge_dependabot_pull_request.yml, .github/workflows/preview.yml
=> ci(github): update pull request preview url continuously

.github/workflows/preview.yml
=> ci(github): upgrade ivangabriele/find-and-replace-pull-request-body to v1.1.2

.github/workflows/merge_dependabot_pull_request.yml, .github/workflows/merge_release_pull_request.yml
=> ci(github): set merge method to rebase in auto-merge workflows

.github/workflows/preview.yml
=> ci(github): upgrade ivangabriele/find-and-replace-pull-request-body to v1.1.3

src/cypress/commands/fill/fillDatePicker.ts, src/cypress/commands/fill/fillDateRangePicker.ts
=> fix(cypress): wrap fill() DatePicker & DateRangePicker selectors within fieldset

src/cypress/commands/fill/fillDatePicker.ts, src/cypress/commands/fill/fillDateRangePicker.ts, src/cypress/commands/fill/fillTextInput.ts, src/cypress/commands/fill/fillTextarea.ts
=> fix(cypress): enable force in fields clearing

src/fields/NumberInput.tsx, src/fields/TextInput.tsx, src/fields/Textarea.tsx
=> fix(fields): Fix value of undefined on controlled inputs

.eslintrc.js, .storybook/components/StoryDecorator.tsx, src/components/NewWindow/index.tsx, src/hooks/useNewWindow/context.ts, src/hooks/useNewWindow/index.ts, src/hooks/useNewWindow/types.ts, src/index.ts, src/types.ts, stories/fields/DatePicker.stories.tsx, stories/fields/DateRangePicker.stories.tsx, stories/fields/MultiSelect.stories.tsx, stories/fields/Search/WithCustomQuery.stories.tsx, stories/fields/Search/WithOptions.stories.tsx, stories/fields/Search/WithOptionsAndCustomMenuItem.stories.tsx, stories/fields/Search/WithQuery.stories.tsx, stories/fields/Select.stories.tsx
=> feat(components): add NewWindow

src/components/NewWindow.tsx
=> fix(components): type all allowed features in NewWindow

src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/index.tsx, stories/fields/DatePicker.stories.tsx, stories/fields/DateRangePicker.stories.tsx, stories/formiks/FormikDatePicker.stories.tsx, stories/formiks/FormikDateRangePicker.stories.tsx
=> fix(fields): add missing isUndefinedWhenDisabled prop to DatePicker & DateRangePicker

src/components/Dialog/Action.tsx, src/components/Dialog/Body.tsx, src/components/Dialog/Title.tsx, src/components/Dialog/index.tsx, src/index.ts, stories/components/Dialog.stories.tsx
=> feat(components): add Dialog

src/components/Dialog/index.tsx
=> fix(components): add default class name to Dialog

src/elements/Button.tsx, src/elements/IconButton.tsx
=> fix(elements): delete stop click event propagation in Button & IconButton

scripts/icons/generateIcons.mjs, src/components/Dialog/index.tsx, src/components/Dropdown/index.tsx, src/components/SingleTag.tsx, src/elements/Button.tsx, src/elements/Field.tsx, src/elements/FieldError.tsx, src/elements/Fieldset.tsx, src/elements/IconBox.tsx, src/elements/IconButton.tsx, src/elements/Label.tsx, src/elements/Legend.tsx, src/elements/Tag/index.tsx, src/elements/TagGroup.tsx, src/fields/CoordinatesInput/index.tsx, src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/index.tsx, src/fields/Search.tsx
=> fix: add missing classnames

src/fields/Search.tsx, stories/fields/Search/WithQuery.stories.tsx, stories/formiks/AutoComplete/WithQuery.stories.tsx
=> fix(fields): delete queryMap and queryUrl props

src/formiks/FormikCheckbox.tsx, src/formiks/FormikCoordinatesInput.tsx, src/formiks/FormikDatePicker.tsx, src/formiks/FormikDateRangePicker.tsx, src/formiks/FormikMultiCheckbox.tsx, src/formiks/FormikMultiRadio.tsx, src/formiks/FormikMultiSelect.tsx, src/formiks/FormikNumberInput.tsx, src/formiks/FormikSearch.tsx, src/formiks/FormikSelect.tsx, src/formiks/FormikTextInput.tsx, src/formiks/FormikTextarea.tsx
- MTES-MCT/monitorfish#1886
https://637e01cf5934a2ae881ccc9d-dbvvyoqcre.chromatic.com/
=> fix(formiks): show error when touched

src/elements/Button.tsx, src/elements/IconButton.tsx, stories/elements/Button.stories.tsx, stories/elements/IconButton.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-fnmcvhsrld.chromatic.com/
=> feat(elements): add withUnpropagatedClick prop to Button & IconButton

.github/workflows/check.yml, .github/workflows/e2e.yml, .github/workflows/preview.yml, .github/workflows/release.yml
None
https://637e01cf5934a2ae881ccc9d-qcoazqnawp.chromatic.com/
=> ci(github): fix release pull request auto-merging

src/fields/DatePicker/CalendarPicker.tsx, src/fields/DateRangePicker/RangeCalendarPicker.tsx
None
https://637e01cf5934a2ae881ccc9d-xetytuukul.chromatic.com/
=> fix(fields): replace deprecated Rsuite disabledDate prop with shouldDisableDate

src/formiks/FormikCheckbox.tsx, src/formiks/FormikCoordinatesInput.tsx, src/formiks/FormikDatePicker.tsx, src/formiks/FormikDateRangePicker.tsx, src/formiks/FormikMultiCheckbox.tsx, src/formiks/FormikMultiRadio.tsx, src/formiks/FormikMultiSelect.tsx, src/formiks/FormikNumberInput.tsx, src/formiks/FormikSearch.tsx, src/formiks/FormikSelect.tsx, src/formiks/FormikTextInput.tsx, src/formiks/FormikTextarea.tsx
- MTES-MCT/monitorfish#1886
https://637e01cf5934a2ae881ccc9d-ibmgnpknui.chromatic.com/
=> fix(formiks): set touched to true on change

e2e/base/fields/MultiSelect.spec.tsx, e2e/base/fields/Select.spec.tsx, src/fields/MultiSelect.tsx, src/fields/Select.tsx, src/libs/CustomSearch.ts
- MTES-MCT/monitorfish#1923
- MTES-MCT/monitorfish#2030
https://637e01cf5934a2ae881ccc9d-onzljlpwjw.chromatic.com/
=> test(fields): add customSearch e2e tests for Select & MultiSelect

e2e/base/fields/Select.spec.tsx, src/libs/CustomSearch.ts
- MTES-MCT/monitorfish#1923
- MTES-MCT/monitorfish#2030
https://637e01cf5934a2ae881ccc9d-ilhisskfkz.chromatic.com/
=> fix(libs): make CustomSearch fully functional

.storybook/data/species.json, src/fields/MultiSelect.tsx, src/fields/Select.tsx, stories/fields/MultiSelect/MultiSelectWithCustomSearch.stories.tsx, stories/fields/Select/SelectWithCustomSearch.stories.tsx
- MTES-MCT/monitorfish#1923
- MTES-MCT/monitorfish#2030
https://637e01cf5934a2ae881ccc9d-kqhdjmosof.chromatic.com/
=> fix(fields): control options internally with customSearch in Select & MultiSelect

src/fields/Search.tsx, stories/fields/Search/WithCustomSearch.stories.tsx
https://637e01cf5934a2ae881ccc9d-iqlbeklasn.chromatic.com/
=> fix(fields): don't display list in Search when no value

src/fields/DateRangePicker/NumberInput.tsx, src/fields/NumberInput.tsx, src/hooks/usePreventWheelEvent.ts
- Resolve MTES-MCT/monitorfish#2087
https://637e01cf5934a2ae881ccc9d-sfgmqmksvg.chromatic.com/
=> fix(fields): prevent wheel event in NumberInput, DatePicker & DateRangePicker

src/fields/DatePicker/index.tsx, src/fields/DateRangePicker/index.tsx, src/fields/MultiRadio.tsx, src/fields/MultiSelect.tsx, src/fields/NumberInput.tsx, src/fields/Select.tsx, src/fields/TextInput.tsx, src/fields/Textarea.tsx
None
https://637e01cf5934a2ae881ccc9d-eckynyfyyv.chromatic.com/
=> fix(fields): add missing and normalize error styles

src/elements/FieldError.tsx
- Resolve MTES-MCT/monitorfish#2060
https://637e01cf5934a2ae881ccc9d-dlodocaxua.chromatic.com/
=> fix(elements): unbold and italicize FieldError

src/components/SideMenu/Button.tsx, src/components/SideMenu/index.tsx
- MTES-MCT/monitorenv#587
https://637e01cf5934a2ae881ccc9d-rmlgugngbj.chromatic.com/
=> fix(components): fix style sideMenu

.github/workflows/release.yml
https://637e01cf5934a2ae881ccc9d-euenfvcpgm.chromatic.com/
=> ci(github): fix node version for release

src/theme.ts
- MTES-MCT/monitorenv#588
https://637e01cf5934a2ae881ccc9d-vpqumrrbsn.chromatic.com/
=> style: add new color

src/assets/icons/MissionAction.svg, src/components/SideMenu/Button.tsx, src/icons/MissionAction.tsx
- MTES-MCT/monitorenv#587
https://637e01cf5934a2ae881ccc9d-mlhokwnvno.chromatic.com/
=> fix(icons): update mission icon

src/assets/icons/Summary.svg, src/icons/Summary.tsx
- MTES-MCT/monitorenv#556
https://637e01cf5934a2ae881ccc9d-swequqwmoz.chromatic.com/
=> fix(icons): update summary icon

e2e/base/fields/CoordinatesInput.spec.tsx, src/fields/CoordinatesInput/DMDCoordinatesInput.tsx
- https://github.com/MTES-MCT/monitorfish/issues/2249
https://637e01cf5934a2ae881ccc9d-nhuxeqqzxx.chromatic.com/
=> feat(fields): add lowercase handling and lower precision in DMD coordinates input 

src/assets/stylesheets/rsuite-override.css, src/elements/Table/TableWithSelectableRows/RowCheckbox.tsx, src/elements/Table/TableWithSelectableRows/index.tsx, src/fields/Checkbox.tsx, src/index.ts, stories/elements/Table/TableWithSelectableRows.stories.tsx
- MTES-MCT/monitorenv#728
https://637e01cf5934a2ae881ccc9d-tkcqovzosm.chromatic.com/
=> (fix)elements: update Checkbox style for TableWithSelectableRows component

src/components/Dropdown/Item.tsx, src/components/Dropdown/index.tsx, src/elements/Table/TableWithSelectableRows/index.tsx, stories/components/Dropdown.stories.tsx, stories/elements/Table/TableWithSelectableRows.stories.tsx
- MTES-MCT/monitorenv#728
https://637e01cf5934a2ae881ccc9d-hndrgregra.chromatic.com/
=> feat(elements): add buttonsGroup component in TableWithSelectableRows component

src/components/MapMenuModal/index.tsx, src/index.ts, stories/components/MapMenuModal.stories.tsx
https://637e01cf5934a2ae881ccc9d-sogavufbjr.chromatic.com/
=> feat(component): create MapMenuModal component

src/components/SingleTag.tsx, stories/components/SingleTag.stories.tsx
- MTES-MCT/monitorenv#722
https://637e01cf5934a2ae881ccc9d-vjltlkgqvo.chromatic.com/
=> feat(components): create secondary accent for single tag component

src/index.ts, src/types.ts
None
https://637e01cf5934a2ae881ccc9d-riyldeiimh.chromatic.com/
=> feat(types): add Filter public type

src/index.ts, src/utils/__tests__/isDefined.test.ts, src/utils/__tests__/pluralize.test.ts, src/utils/pluralize.ts
None
https://637e01cf5934a2ae881ccc9d-mvrfxngdsz.chromatic.com/
=> feat(utils): add pluralize()

e2e/base/fields/CoordinatesInput.spec.tsx, src/utils/__tests__/coordinates.test.ts, src/utils/coordinates.ts
- https://github.com/MTES-MCT/monitorfish/issues/2376
https://637e01cf5934a2ae881ccc9d-gsoblivxxn.chromatic.com/
=> fix(utils): fix getCoordinates rounding

README.md, package.json
None
https://637e01cf5934a2ae881ccc9d-pixyxvnggo.chromatic.com/
=> docs(readme): add RapportNav in description

src/tables/DataTable/index.tsx
- MTES-MCT/monitorenv#509
https://637e01cf5934a2ae881ccc9d-rfmmqyxoir.chromatic.com/
=> fix(tables): remove secondary generic type in DataTable

src/elements/Button.tsx, stories/elements/Button.stories.tsx
Large and normal buttons were having the same sizes. 
I took inspiration from IconButton and accordingly updated the size of the large button.
=> Update settings for large button

src/theme.ts
- https://github.com/MTES-MCT/monitorfish/issues/1211
https://637e01cf5934a2ae881ccc9d-nryhxquwno.chromatic.com/
=> feat(theme): add custom zones colors

src/assets/icons/Link.svg, src/assets/icons/Unlink.svg, src/icons/Link.tsx, src/icons/Unlink.tsx, src/icons/index.tsx, stories/Icon.stories.tsx
https://637e01cf5934a2ae881ccc9d-xnyewswvhb.chromatic.com/
=> feat(icons): add Link and Unlink icons

src/assets/icons/EditUnbordered.svg, src/icons/EditUnbordered.tsx, src/icons/index.tsx, stories/Icon.stories.tsx
- https://github.com/MTES-MCT/monitorfish/issues/1211
https://637e01cf5934a2ae881ccc9d-tounkejqyr.chromatic.com/
=> feat(icons): add EditUnbordered icon

e2e/base/tables/DataTable.spec.tsx, src/cypress/commands/getTableRowById.ts, src/cypress/global.d.ts, src/cypress/index.ts, src/index.ts, src/tables/DataTable/index.tsx, src/tables/SimpleTable.tsx, src/types.ts, stories/tables/DataTable.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-pkcjtvtikg.chromatic.com/
=> feat(cypress): add getTableRowById() custom command

.commitlintrc, .releaserc
None
https://637e01cf5934a2ae881ccc9d-rpmemwfjik.chromatic.com/
=> ci(semantic-release): include deps upgrades in release notes

src/fields/MultiRadio.tsx, src/types.ts, stories/fields/MultiRadio.stories.tsx
- Resolve #123
- MTES-MCT/monitorenv#836
https://637e01cf5934a2ae881ccc9d-ivvyhcywdv.chromatic.com/
=> feat(field): add disabled prop on Option type to handle case where only certain options are disabled

.github/workflows/check.yml, .github/workflows/e2e.yml, .github/workflows/timezone.yml
None
https://637e01cf5934a2ae881ccc9d-kqyxaelhma.chromatic.com/
=> ci(github): schedule timezoned tests to run once a day on main branch

src/elements/Tag/index.tsx, stories/elements/Tag.stories.tsx
https://637e01cf5934a2ae881ccc9d-vxrkcbkcgu.chromatic.com/
=> fix(elements): add backgroundColor and borderColor props and fix icon size in Tag component

package.json, yarn.lock
- #827
https://637e01cf5934a2ae881ccc9d-gjnbiythbs.chromatic.com/
=> feat: extend styled-components to v6 in peer deps

.github/workflows/release.yml
None
https://637e01cf5934a2ae881ccc9d-advgkdqopk.chromatic.com/
=> ci(github): fix node version in deploy job

e2e/release/sample/package-lock.json, e2e/release/sample/package.json, package.json, yarn.lock
- Resolve #123
- MTES-MCT/monitorenv#123
- MTES-MCT/monitorfish#123
https://637e01cf5934a2ae881ccc9d-xgxqwsmnyv.chromatic.com/
=> ci(commitlint): remove @ivangabriele/commitlint-config dev deps

src/fields/MultiSelect.tsx
- MTES-MCT/monitorenv#921
https://637e01cf5934a2ae881ccc9d-qkagpybcpr.chromatic.com/
=> fix(field): fix MultiSelect when disabled

src/fields/Select.tsx
- MTES-MCT/monitorenv#921
https://637e01cf5934a2ae881ccc9d-mqtjhlsygw.chromatic.com/
=> fix(field): fix Select when disabled

src/theme.ts
https://github.com/MTES-MCT/monitorfish/issues/1450
https://637e01cf5934a2ae881ccc9d-wqpnepzfec.chromatic.com/
=> fix(theme): replace goldenPoppy25 color

package.json
https://637e01cf5934a2ae881ccc9d-anrsgmhovg.chromatic.com/
=> fix(icons): fix command to generate icons

src/elements/Tag/Disk.tsx, src/elements/Tag/index.tsx, stories/elements/Tag.stories.tsx
- MTES-MCT/monitorenv#944
https://637e01cf5934a2ae881ccc9d-drdrsmptqo.chromatic.com/
=> feat(elements): use Dot icon for bullet in tag component

e2e/base/fields/CkeckPicker.spec.tsx, e2e/base/fields/MultiSelect.spec.tsx, e2e/base/fields/Select.spec.tsx, src/fields/CheckPicker.tsx, src/fields/MultiSelect.tsx, src/fields/Select.tsx
- MTES-MCT/monitorenv#372
https://637e01cf5934a2ae881ccc9d-mgckjcnwul.chromatic.com/
=> fix(fields): return all results when user delete search in CheckPicker, Select and MultiSelect

.github/dependabot.yml
None
https://637e01cf5934a2ae881ccc9d-qymkldguze.chromatic.com/
=> ci(dependabot): change auto-update frequency from weekly to monthly interval

src/fields/CheckPicker.tsx
https://637e01cf5934a2ae881ccc9d-vlswgnylsj.chromatic.com/
=> fix(elements): fix checkpicker style

.github/dependabot.yml
=> ci(dependabot): update labels

.github/workflows/check.yml, .github/workflows/e2e.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/timezone.yml, e2e/release/sample/package-lock.json, e2e/release/sample/package.json, package.json
None
https://637e01cf5934a2ae881ccc9d-jzitccnqje.chromatic.com/
=> build: migrate Node from v18 to v20

yarn.lock
None
https://637e01cf5934a2ae881ccc9d-otkfvcspvj.chromatic.com/
=> build(yarn): fix lock file

package.json, yarn.lock
This reverts commit a1f3f24712567779d9bdfa2de2a9330029ead9c3.
None
https://637e01cf5934a2ae881ccc9d-gwueitwtgz.chromatic.com/
=> build(peer-deps): revert "build(dev-deps): bump styled-components from 5.3.10 to 6.1.1"

package.json, src/fields/DateRangePicker/RangeCalendarPicker.tsx, yarn.lock
https://637e01cf5934a2ae881ccc9d-cwkxxkbfln.chromatic.com/
=> fix(fields): fix date picker size

src/fields/MultiCheckbox.tsx, stories/fields/MultiCheckbox.stories.tsx
- MTES-MCT/monitorenv#1005
https://637e01cf5934a2ae881ccc9d-okpvjzwfbg.chromatic.com/
=> feat(field): handle disabled prop on options in MultiCheckbox component

src/entities/Administration.ts, src/entities/ControlUnit.ts, src/entities/DepartmentArea.ts, src/entities/Mission.ts, src/entities/Station.ts, src/index.ts
- MTES-MCT/monitorenv#698
https://637e01cf5934a2ae881ccc9d-fpojbycnzq.chromatic.com/
=> feat(entities): add Administration, ControlUnit, DepartmentArea & Station

src/assets/stylesheets/rsuite-override.css
Je me sers du Toggle component de rsuite donc je rajoute quelques styles n plus concernant ce component.
A terme, je compte rajouter le Toggle dans monitor-ui
https://637e01cf5934a2ae881ccc9d-whomzvqsso.chromatic.com/
=> chore(css-override): add colors for Toggle

src/theme.ts
https://637e01cf5934a2ae881ccc9d-xdanabwdlt.chromatic.com/
=> feat(theme): add medium sea green 25 color

src/fields/Select.tsx
https://637e01cf5934a2ae881ccc9d-aygwhdcysu.chromatic.com/
=> fix(fields): fix disabled prop in select component

src/hooks/useDeepCompareEffect.ts, src/index.ts
https://637e01cf5934a2ae881ccc9d-yytsqnlhsf.chromatic.com/
=> feat(hooks): add useDeepCompareEffect

src/components/MapMenuDialog/index.tsx, stories/components/MapMenuModal.stories.tsx
- MTES-MCT/monitorenv#698
https://637e01cf5934a2ae881ccc9d-xhyuayzyfc.chromatic.com/
=> fix(components): truncate long titles in MapMenuDialog

e2e/base/fields/DateRangePicker.spec.tsx, src/cypress/commands/waitForLastRequest.ts, src/cypress/global.d.ts
https://637e01cf5934a2ae881ccc9d-qsvyxecngc.chromatic.com/
=> feat(cypress): add callback to waitForLastRequest command

src/fields/TextInput.tsx, stories/fields/TextInput.stories.tsx
- MTES-MCT/monitorenv#1043
https://637e01cf5934a2ae881ccc9d-vskyvvtrog.chromatic.com/
=> feat(field): add isSearchInput prop to display Search and close icons

src/tables/TableWithSelectableRows/index.tsx, stories/tables/TableWithSelectableRows.stories.tsx
- MTES-MCT/monitorenv#1118
https://637e01cf5934a2ae881ccc9d-gapmfqvlkd.chromatic.com/
=> fix(table): update padding in row and add prop isHighlight

src/tables/TableWithSelectableRows/index.tsx, stories/tables/TableWithSelectableRows.stories.tsx
- MTES-MCT/monitorenv#1118
Changement de la gestion du tableau -> passage en taille fixe avec taille des colonnes en fixe également
https://637e01cf5934a2ae881ccc9d-tuuseakfdm.chromatic.com/
=> fix(table)!: add width prop in TableWithSelectableRows.Td

CHANGELOG.md, package.json
None
https://637e01cf5934a2ae881ccc9d-rbrbkuiron.chromatic.com/
=> ci(release): fix versioning history

src/assets/icons/Attention.svg, src/icons/Attention.tsx
- MTES-MCT/monitorenv#1123
https://637e01cf5934a2ae881ccc9d-kgpnitksst.chromatic.com/
=> fix(icon): fix Attention icon

src/components/MapMenuDialog/index.tsx
- MTES-MCT/monitorenv#1105
https://637e01cf5934a2ae881ccc9d-fxdluphlqj.chromatic.com/
=> feat(components): allow title prop on MapMenuDialog.Title

src/entities/ControlUnit.ts
None
https://637e01cf5934a2ae881ccc9d-anizsuggvc.chromatic.com/
=> feat(entities): add ControlUnitResourceCategory enum

src/types.ts, src/utils/getOptionsFromLabelledEnum.ts
None.
https://637e01cf5934a2ae881ccc9d-jwpzsmdmhm.chromatic.com/
=> fix(utils): add missing generic type in getOptionsFromLabelledEnum()

src/components/Message.tsx, src/constants.ts, src/elements/Button.tsx, stories/components/Message.stories.tsx, stories/elements/Button.stories.tsx
- MTES-MCT/monitorenv#1119
https://637e01cf5934a2ae881ccc9d-xycvufkubx.chromatic.com/
=> feat(components): add warning accent for Buttons

src/index.ts
None
https://637e01cf5934a2ae881ccc9d-cijzendyjs.chromatic.com/
=> fix(types): expose missing PartialExcept & UndefineExcept

src/assets/icons/Warning.svg, src/icons/Warning.tsx, src/icons/index.tsx, stories/Icon.stories.tsx
- MTES-MCT/monitorenv#1184
https://637e01cf5934a2ae881ccc9d-sfvofssjvc.chromatic.com/
=> feat(icons): add warning icon

src/fields/MultiRadio.tsx
- MTES-MCT/monitorenv#1188
https://637e01cf5934a2ae881ccc9d-nbembjxkth.chromatic.com/
=> fix(fields): fix MultiRadio colors

src/assets/stylesheets/rsuite-override.css, src/fields/MultiRadio.tsx, src/fields/Toggle.tsx
- MTES-MCT/monitorenv#1188
https://637e01cf5934a2ae881ccc9d-gjsxbbjiun.chromatic.com/
=> fix(fields): update background color for MultiRadio component

src/entities/ControlUnit/types.ts
- MTES-MCT/monitorfish#2925
https://637e01cf5934a2ae881ccc9d-apujgogagy.chromatic.com/
=> fix(type): update EngagedControlUnit type

src/utils/getRsuiteDataItemValueFromOptionValue.ts
None
https://637e01cf5934a2ae881ccc9d-jrxvlwqkkj.chromatic.com/
=> fix(fields): handle missing boolean option value case in options fields

src/fields/MultiCheckbox.tsx
- MTES-MCT/monitorfish#2959
https://637e01cf5934a2ae881ccc9d-kxyauctmnf.chromatic.com/
=> style(fields): fix MultiCheckbox options margin when isInline

.github/workflows/e2e-next.yml, .github/workflows/timezone.yml, config/cypress.config.ts, src/cypress/utils/findElementParentBySelector.ts, src/utils/__tests__/humanizePastDate.test.ts
https://637e01cf5934a2ae881ccc9d-bpaivxjxym.chromatic.com/
=> fix(cypress): handle nested fieldsets in fill() command

.github/workflows/merge_dependabot_pull_request.yml, .github/workflows/preview.yml
None
https://637e01cf5934a2ae881ccc9d-qjmthwxupx.chromatic.com/
=> ci(github): enable Preview workflow on main branch

README.md
None
https://637e01cf5934a2ae881ccc9d-wiylspelbg.chromatic.com/
=> docs(readme): add documentation badge

package.json, src/cypress/commands/fill/pickMultiSelectOptions.ts, src/cypress/commands/forceClick.ts, yarn.lock
https://637e01cf5934a2ae881ccc9d-tersdqpfpn.chromatic.com/
=> fix(cypress): use forced click instead of click in fill() on MultiSelect

.github/workflows/e2e.yml, e2e/base/fields/MultiCheckbox.spec.tsx, src/cypress/commands/fill/checkCheckbox.ts, src/cypress/commands/fill/checkMultiCheckboxOptions.ts, src/cypress/commands/fill/fillDatePicker.ts, src/cypress/commands/fill/fillDateRangePicker.ts, src/cypress/commands/fill/fillNumberInput.ts, src/cypress/commands/fill/fillTextInput.ts, src/cypress/commands/fill/fillTextarea.ts, src/cypress/commands/fill/pickCheckPickerOptions.ts, src/cypress/commands/fill/pickMultiSelectOptions.ts, src/cypress/commands/fill/pickSearchOption.ts, src/cypress/commands/fill/pickSelectOption.ts, src/cypress/commands/forceCheck.ts, src/cypress/commands/forceClear.ts, src/cypress/commands/forceType.ts, src/cypress/commands/forceUncheck.ts, src/cypress/global.d.ts, src/cypress/index.ts, src/cypress/libs/RetryError.ts, src/cypress/utils/ensureElement.ts
https://637e01cf5934a2ae881ccc9d-mwuagksnyc.chromatic.com/
=> fix(cypress): force all actions in fill() subcommands

src/cypress/commands/fill/checkCheckbox.ts, src/cypress/commands/fill/checkMultiCheckboxOptions.ts, src/cypress/commands/fill/checkMultiRadioOption.ts, src/cypress/commands/fill/constants.ts, src/cypress/commands/fill/fillDatePicker.ts, src/cypress/commands/fill/fillDateRangePicker.ts, src/cypress/commands/fill/fillNumberInput.ts, src/cypress/commands/fill/fillTextInput.ts, src/cypress/commands/fill/fillTextarea.ts, src/cypress/commands/fill/index.ts, src/cypress/commands/fill/pickCheckPickerOptions.ts, src/cypress/commands/fill/pickMultiSelectOptions.ts, src/cypress/commands/fill/pickSearchOption.ts, src/cypress/commands/fill/pickSelectOption.ts, src/cypress/global.d.ts
None
https://637e01cf5934a2ae881ccc9d-njvnyivljx.chromatic.com/
=> feat(cypress): add force option to fill() command

src/utils/__tests__/humanizePastDate.test.ts, src/utils/humanizePastDate.ts
- MTES-MCT/monitorenv#1242
https://637e01cf5934a2ae881ccc9d-jczkygbjvs.chromatic.com/
=> feat(utils): delete "(UTC)"  from humanizePastDate function

src/cypress/commands/fill/constants.ts, src/cypress/commands/fill/fillDatePicker.ts, src/cypress/commands/fill/fillDateRangePicker.ts, src/cypress/commands/fill/fillNumberInput.ts, src/cypress/commands/fill/fillTextInput.ts, src/cypress/commands/fill/fillTextarea.ts, src/cypress/commands/fill/index.ts, src/cypress/commands/fill/pickCheckPickerOptions.ts, src/cypress/commands/fill/pickMultiSelectOptions.ts, src/cypress/commands/fill/pickSearchOption.ts, src/cypress/commands/fill/pickSelectOption.ts, src/cypress/global.d.ts, src/fields/Search.tsx
https://637e01cf5934a2ae881ccc9d-rukitucvnj.chromatic.com/
=> feat(cypress): add delay option to fill command

src/cypress/commands/waitForLastRequest.ts
https://637e01cf5934a2ae881ccc9d-kszlskxjwu.chromatic.com/
=> fix(cypress): fix function waitForLastRequestFunction

src/components/Dialog/Action.tsx, src/components/Message.tsx, src/utils/__tests__/humanizePastDate.test.ts, src/utils/humanizePastDate.ts
https://637e01cf5934a2ae881ccc9d-cnidmyuijl.chromatic.com/
=> fix(components): update some style and fix typo

src/utils/__tests__/getFilteredCollection.test.ts, src/utils/getFilteredCollection.ts
https://637e01cf5934a2ae881ccc9d-mgxpppfpbn.chromatic.com/
=> fix(utils): remove conditional types from getFilteredCollection()

config/jest.config.js, src/tables/TableWithSelectableRows/RowCheckbox.tsx, src/utils/stopMouseEventPropagation.ts, tsconfig.json
https://637e01cf5934a2ae881ccc9d-gkcaasltbm.chromatic.com/
=> fix(tables): stop click event propagation in RowCheckbox

src/components/Dialog/Action.tsx, src/components/Dialog/Body.tsx, stories/components/Dialog.stories.tsx
- MTES-MCT/monitorenv#1241
https://637e01cf5934a2ae881ccc9d-otepfazead.chromatic.com/
=> fix(components): update Dialog padding

e2e/base/fields/MultiSelect.spec.tsx, src/cypress/commands/fill/pickMultiSelectOptions.ts
https://637e01cf5934a2ae881ccc9d-cupexrlqhr.chromatic.com/
=> fix(cypress): handle searchable MultiSelect in fill() command

e2e/base/fields/MultiRadio.spec.tsx, src/fields/MultiRadio.tsx, stories/fields/MultiRadio.stories.tsx
- Corrige la sélection des checkbox pour les booléens (UI et logique)
https://637e01cf5934a2ae881ccc9d-neixfiynoz.chromatic.com/
=> fix(fields): fix MultiRadio with booleans

e2e/base/fields/CheckPicker.spec.tsx, e2e/base/fields/MultiCascader.spec.tsx, e2e/base/fields/MultiCheckbox.spec.tsx, e2e/base/fields/MultiRadio.spec.tsx, e2e/base/fields/MultiSelect.spec.tsx, e2e/base/fields/Search.spec.tsx, e2e/base/fields/Select.spec.tsx, src/cypress/commands/fill/index.ts, src/cypress/commands/fill/pickCheckPickerOptions.ts, src/cypress/commands/fill/pickMultiCascaderOptions.ts, src/fields/CheckPicker.tsx
https://637e01cf5934a2ae881ccc9d-afirjslrkc.chromatic.com/
=> fix(cypress): clear CheckPicker search input in fill() command

src/assets/icons/ControlUnit.svg, src/assets/icons/ControlUnitFilled.svg, src/icons/ControlUnit.tsx, src/icons/ControlUnitFilled.tsx
- MTES-MCT/monitorfish#2959
https://637e01cf5934a2ae881ccc9d-ihamovzaox.chromatic.com/
=> fix(icons): fix controlUnit and controlUnitFilled icons

src/assets/icons/Account.svg, src/assets/icons/Logout.svg, src/icons/Account.tsx, src/icons/Logout.tsx, src/icons/index.tsx
- https://github.com/MTES-MCT/monitorfish/issues/2763
https://637e01cf5934a2ae881ccc9d-latkdfpbow.chromatic.com/
=> feat(icons): add new icons

e2e/base/components/Banner.spec.tsx, src/components/Banner/index.tsx, stories/components/Banner.stories.tsx
- MTES-MCT/monitorenv#1285
https://637e01cf5934a2ae881ccc9d-dmbmstoqyu.chromatic.com/
=> feat(components): add automatic closing on Banner component

src/components/Message/index.tsx
https://637e01cf5934a2ae881ccc9d-hbcrclawil.chromatic.com/
=> fix(components): add missing class name and replace span box with div in Message

src/components/Message/index.tsx, src/elements/IconButton.tsx
https://637e01cf5934a2ae881ccc9d-zgjmvgytfh.chromatic.com/
=> style: specify solid border in IconButton & Message

src/entities/ControlUnit/types.ts
https://637e01cf5934a2ae881ccc9d-gbwztbyecn.chromatic.com/
=> feat(entities)!: add new ControlUnitContact props

src/components/Banner/index.tsx, src/elements/IconButton.tsx, stories/components/Banner.stories.tsx, stories/elements/IconButton.stories.tsx
https://637e01cf5934a2ae881ccc9d-igijqswrwf.chromatic.com/
=> feat(components): clean Banner and add new props

src/components/Banner/index.tsx
https://637e01cf5934a2ae881ccc9d-mnqitenvkb.chromatic.com/
=> feat(components): add on auto close prop to banner

src/components/Banner/index.tsx
https://637e01cf5934a2ae881ccc9d-awdzhauwho.chromatic.com/
=> feat(components): add onClose prop to Banner

.storybook/components/Output.tsx, e2e/base/components/Banner.spec.tsx, src/components/Banner/constants.ts, src/components/Banner/index.tsx, src/elements/Link.tsx, stories/components/Banner.stories.tsx
https://637e01cf5934a2ae881ccc9d-xecnrfktzh.chromatic.com/
=> fix(components): fix on auto close prop callback in Banner

src/index.ts, src/types/definitions.ts
- MTES-MCT/monitorfish#2843
https://637e01cf5934a2ae881ccc9d-cetfmhbquz.chromatic.com/
=> fea(types): add AnyEnum

src/types/definitions.ts
- MTES-MCT/monitorfish#2843
https://637e01cf5934a2ae881ccc9d-hghjdgpuag.chromatic.com/
=> fix(types): fix AnyEnum key type

src/elements/IconButton.tsx
https://637e01cf5934a2ae881ccc9d-cpfhdqztwi.chromatic.com/
=> fix(elements): fix IconButton border

src/tables/SimpleTable/index.tsx, src/tables/TableWithSelectableRows/index.tsx
- MTES-MCT/monitorfish#2843
https://637e01cf5934a2ae881ccc9d-cfrmtngvct.chromatic.com/
=> fix(tables): fix multiple issues in SimpleTable & TableWithSelectableRows

src/fields/DateRangePicker/RangeCalendarPicker.tsx, src/fields/shared/StyledRsuiteCalendarBox.ts
None
https://637e01cf5934a2ae881ccc9d-pcvwvyqtwc.chromatic.com/
=> fix(fields): set calendar range popup width in DateRangePicker

src/fields/Search.tsx
https://637e01cf5934a2ae881ccc9d-inygiphrli.chromatic.com/
=> fix(fields):  remove useKey

.github/workflows/check.yml, .github/workflows/e2e.yml, .github/workflows/preview.yml, src/assets/icons/Send.svg, src/icons/Send.tsx, src/icons/index.tsx
- MTES-MCT/monitorfish#3241
https://637e01cf5934a2ae881ccc9d-nzugmpzeed.chromatic.com/
=> feat(icons): add Send

.github/workflows/merge_release_pull_request.yml, CONTRIBUTING.md
None
https://637e01cf5934a2ae881ccc9d-zhxwvfxukd.chromatic.com/
=> docs(contributing): update release instructions

.github/dependabot.yml
None
https://637e01cf5934a2ae881ccc9d-aqrsdvidep.chromatic.com/
=> ci(dependabot): group non-major non-security dependency upgrades

.github/dependabot.yml
None
https://637e01cf5934a2ae881ccc9d-wdwafsixsz.chromatic.com/
=> ci(dependabot): include prod deps & security updates in e2e release group

src/components/Dropdown/index.tsx
- [MTES-MCT/monitorfish#123](https://github.com/MTES-MCT/monitorfish/issues/3288#issuecomment-2186627954)
https://637e01cf5934a2ae881ccc9d-alkmgiwfor.chromatic.com/
=> feat(components): fix secondary dropdown

src/theme.ts
- MTES-MCT/monitorenv#1477
https://637e01cf5934a2ae881ccc9d-aeanqdggil.chromatic.com/
=> feat(components): add new color for vigilance areas

src/fields/shared/StyledInputBox.ts
- Search box padding
https://637e01cf5934a2ae881ccc9d-zblcxuchnu.chromatic.com/
=> fix(components): input box properties should override input ones

src/components/Dropdown/index.tsx, stories/components/Dropdown.stories.tsx
https://637e01cf5934a2ae881ccc9d-ctennqxlcg.chromatic.com/
=> fix(components): add tertiary to dropdown

e2e/base/fields/PhoneInput.spec.tsx, src/fields/PhoneInput.tsx
- MTES-MCT/monitorenv#1530
https://637e01cf5934a2ae881ccc9d-wdccoimyyb.chromatic.com/
=> Numéro de téléphone: Ajout d'un mask pour le format français international

src/elements/Label.tsx, src/fields/CheckPicker.tsx, src/fields/MultiCascader/index.tsx, src/fields/MultiSelect.tsx, src/fields/NumberInput.tsx, src/fields/PhoneInput.tsx, src/fields/Search.tsx, src/fields/Select.tsx, src/fields/TextInput.tsx, src/fields/Textarea.tsx, src/fields/Toggle/index.tsx, stories/elements/Label.stories.tsx
Reverts MTES-MCT/monitor-ui#1264
=> Revert "[A11Y]: Modification de la propriété isHidden pour rendre le label accessible"

src/fields/TextInput.tsx, src/fields/shared/StyledInputBox.ts
- Resolve https://github.com/MTES-MCT/monitorenv/issues/1448
https://637e01cf5934a2ae881ccc9d-ogqzyddkrg.chromatic.com/
=> [Input de recherche]: Ajout d'un padding a droite pour les icones et Modification du padding en bas pour les champs LARGE

src/fields/TextInput.tsx
https://637e01cf5934a2ae881ccc9d-qifsamefsf.chromatic.com/
=> [TextInput]: Ajout de padding à droite quand on est en mode search

src/index.ts, src/utils/customDayjs.ts
- MTES-MCT/monitorenv#1586
https://637e01cf5934a2ae881ccc9d-vantrsjbnn.chromatic.com/
=> feat(utils): add new dayjs plugin( `isBetween`)

CHANGELOG.md, package.json
https://637e01cf5934a2ae881ccc9d-utgejlwgwr.chromatic.com/
=> ci(release): 18.9.0

src/assets/icons/Invalid.svg, src/icons/Invalid.tsx, src/icons/index.tsx
- https://github.com/MTES-MCT/monitorfish/issues/3428
https://637e01cf5934a2ae881ccc9d-hoqkimkorb.chromatic.com/
=> feat(icons): add invalid icon

package.json, yarn.lock
None
https://637e01cf5934a2ae881ccc9d-cnqpnawsrl.chromatic.com/
=> build(peer-deps): allow @sentry/react v7

src/elements/IconButton.tsx, stories/fields/MultiRadio.stories.tsx
https://637e01cf5934a2ae881ccc9d-fyphawpina.chromatic.com/
=> feat(elements): pass class name to icon button

src/elements/IconButton.tsx
https://637e01cf5934a2ae881ccc9d-mxinkqbpea.chromatic.com/
=> fix(elements): remove div wrapper

src/assets/icons/ListLines.svg, src/icons/ListLines.tsx, src/icons/index.tsx
`See Icons > ListLines`
https://637e01cf5934a2ae881ccc9d-ubuhsyhdcm.chromatic.com/
=> [Icons] Add a new icon for lists

.eslintrc.cjs, src/fields/NumberInput.tsx, stories/fields/NumberInput.stories.tsx
- MTES-MCT/monitorfish#3398
https://637e01cf5934a2ae881ccc9d-wimzfgpgga.chromatic.com/
=> feat(fields): add areArrowsHidden prop to NumberInput

.github/workflows/check.yml, .github/workflows/e2e.yml, .github/workflows/timezone.yml
None
https://637e01cf5934a2ae881ccc9d-qwfppydzez.chromatic.com/
=> ci(github): fix release PR exclusion condition

.github/workflows/merge_release_pull_request.yml
None
https://637e01cf5934a2ae881ccc9d-wznrjddopd.chromatic.com/
=> ci(github): increase retries to 120 in Merge Release Pull Request worflow

src/fields/NumberInput.tsx, stories/fields/NumberInput.stories.tsx
- MTES-MCT/monitorfish#3508
https://637e01cf5934a2ae881ccc9d-duifddatdf.chromatic.com/
=> feat(fields): add unit prop to NumberInput

src/elements/SingleTag.tsx
- MTES-MCT/monitorfish#3666
https://637e01cf5934a2ae881ccc9d-wplhcfzppu.chromatic.com/
=> style(elements): fix close button size in SingleTag

src/components/NewWindow.tsx
None
https://637e01cf5934a2ae881ccc9d-cdlcforbax.chromatic.com/
=> refactor(components): simplify stylesheets injection in NewWindow

src/fields/Select.tsx
None
https://637e01cf5934a2ae881ccc9d-mdlvatpnmg.chromatic.com/
=> fix(fields): handle id with special chars in Select pointer-events hack

config/jest.config.js, src/elements/Button/BaseButton.tsx, src/elements/Button/index.tsx, src/elements/IconButton/BaseIconButton.tsx, src/elements/IconButton/index.tsx, src/elements/SingleTag.tsx, tsconfig.json
- MTES-MCT/monitorfish#3666
https://637e01cf5934a2ae881ccc9d-frghchkuzb.chromatic.com/
=> fix(elements): uncouple SingleTag from IconButton

.eslintrc.cjs, src/cypress/commands/clickButton.ts, src/cypress/global.d.ts
None
https://637e01cf5934a2ae881ccc9d-tsawmqrzda.chromatic.com/
=> feat(cypress): add withoutScroll option to clickButton()

src/fields/Select.tsx
- MTES-MCT/monitorfish#3700
https://637e01cf5934a2ae881ccc9d-sdacsmstzl.chromatic.com/
=> feat(fields): rollback pointer-events hack in Select

src/utils/customDayjs.ts
None
https://637e01cf5934a2ae881ccc9d-cziwqpiyoa.chromatic.com/
=> feat(utils): add relativeTime extension to customDayjs

src/index.ts
None
https://637e01cf5934a2ae881ccc9d-rlpdejweeq.chromatic.com/
=> fix(utils): add missing customDayjs typings for relativeTime extension

e2e/base/fields/DateRangePicker.spec.tsx, src/fields/DateRangePicker/index.tsx
https://637e01cf5934a2ae881ccc9d-juiqyhxqjd.chromatic.com/
=> feat(fields): add hasFullDayDefaultValue to date range picker

__mocks__/fake_table_columns_and_data.ts, e2e/base/tables/DataTable.spec.tsx, src/tables/DataTable/index.tsx, src/tables/SimpleTable/Td.tsx, stories/tables/DataTable.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-ktuvalzjpl.chromatic.com/
=> feat(tables): add tableOptions & isTableHeadHidden props to DataTable

src/tables/DataTable/index.tsx, stories/tables/DataTable.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-vxtbxhpikz.chromatic.com/
=> fix(tables): make DataTable tableOptions prop partial

src/assets/icons/VigilanceAreas.svg, src/icons/VigilanceAreas.tsx, src/icons/index.tsx, yarn.lock
- MTES-MCT/monitorenv#1781
https://637e01cf5934a2ae881ccc9d-xozjcmvkwg.chromatic.com/
=> feat(icons): add vigilanceAreas icon

src/assets/icons/SelectPolygon.svg, src/assets/icons/SelectRectangle.svg, src/icons/SelectPolygon.tsx, src/icons/SelectRectangle.tsx
- MTES-MCT/monitorenv#1810
https://637e01cf5934a2ae881ccc9d-aywushrhaj.chromatic.com/
=> feat(icons): modify icons for selection [rectangle and polygon]

src/cypress/commands/clickButton.ts
None
https://637e01cf5934a2ae881ccc9d-uxieahceop.chromatic.com/
=> feat(cypress): add button role support to clickButton()

commitlint.config.js, scripts/build/copyPublicFiles.sh
https://637e01cf5934a2ae881ccc9d-jnpekapwjn.chromatic.com/
=> [Font] export des fonts lors du build

.storybook/constants.tsx, src/tables/DataTable/index.tsx, stories/tables/DataTable.stories.tsx
None
https://637e01cf5934a2ae881ccc9d-ygryuywted.chromatic.com/
=> feat(tables): add emptyLabel prop to DataTable

src/components/Message/index.tsx
https://637e01cf5934a2ae881ccc9d-bmnkgmnkuj.chromatic.com/
=> fix(components): fix margin when there is no icon

.github/workflows/e2e.yml, .github/workflows/merge_dependabot_pull_request.yml, .github/workflows/merge_release_pull_request.yml, .github/workflows/preview.yml, .github/workflows/release.yml, src/theme.ts
- MTES-MCT/monitorenv#1875
https://637e01cf5934a2ae881ccc9d-itommznfug.chromatic.com/
=> style(global): add champagne pink color to vigilance areas

src/assets/icons/Stroke.svg, src/icons/Stroke.tsx, src/icons/index.tsx
- MTES-MCT/monitorenv#1881
https://637e01cf5934a2ae881ccc9d-lckbhmnpur.chromatic.com/
=> feat(icons): add Stroke icon

src/components/Dropdown/Item.tsx, src/components/Dropdown/index.tsx, src/components/SideMenu/Button.tsx, src/elements/SingleTag.tsx, src/fields/DateRangePicker/TimeInput.tsx, yarn.lock
https://637e01cf5934a2ae881ccc9d-zfahedmvey.chromatic.com/
=> fix(elements): fix prefixed props

src/elements/Label.tsx, src/elements/Legend.tsx
https://637e01cf5934a2ae881ccc9d-yeypelspej.chromatic.com/
=> fix(elements): fix $isRequired prop on label and Legend components

package.json
https://github.com/semantic-release/release-notes-generator/issues/657
https://637e01cf5934a2ae881ccc9d-lomkavggfo.chromatic.com/
=> fix(global): resolve issue when releasing new version

package.json, yarn.lock
https://637e01cf5934a2ae881ccc9d-ygwcwdrqqb.chromatic.com/
=>  update dependencies to fix release job

package.json, yarn.lock
https://637e01cf5934a2ae881ccc9d-qvttflzxla.chromatic.com/
=> chore(dependencies): remove tanstack dependencies from devdependencies and upgrade it to latest version

.storybook/data/tags.json, src/fields/CheckPicker.tsx, src/fields/CheckTreePicker/__tests__/utils.test.ts, src/fields/CheckTreePicker/index.tsx, src/fields/CheckTreePicker/types.ts, src/fields/CheckTreePicker/utils.ts, src/fields/shared/CheckPickerBox.tsx, src/fields/shared/StyledRsuitePickerBox.ts, src/formiks/FormikCheckTreePicker.tsx, stories/fields/CheckTreePicker.stories.tsx, stories/formiks/FormikCheckTreePicker.stories.tsx
Base component is from [rsuite](https://rsuitejs.com/components/check-tree-picker/) with `cascade={false}`. 
Difference with base component : 
| BASE COMPONENT | THIS COMPONENT |
|:---:|:---:|
returns an array of string | returns an array of TreeOption
select child **doesn't select** parent | select child **select** parent
- MTES-MCT/monitorenv#2152
https://637e01cf5934a2ae881ccc9d-cfnymxygxk.chromatic.com/
=> Create CheckTreePicker components

src/formiks/FormikCheckPicker.tsx, src/formiks/FormikCheckTreePicker.tsx, src/formiks/FormikCheckbox.tsx, src/formiks/FormikDatePicker.tsx, src/formiks/FormikDateRangePicker.tsx, src/formiks/FormikMultiCascader.tsx, src/formiks/FormikMultiCheckbox.tsx, src/formiks/FormikMultiRadio.tsx, src/formiks/FormikMultiSelect.tsx, src/formiks/FormikNumberInput.tsx, src/formiks/FormikPhoneInput.tsx, src/formiks/FormikRichBooleanCheckbox.tsx, src/formiks/FormikSearch.tsx, src/formiks/FormikSelect.tsx, src/formiks/FormikTextInput.tsx, src/formiks/FormikTextarea.tsx, src/formiks/FormikToggle.tsx
https://637e01cf5934a2ae881ccc9d-llcaoopbkd.chromatic.com/
=> chore(formik): remove useless useffect

e2e/base/fields/CheckTreePicker.spec.tsx, src/cypress/commands/fill/index.ts, src/cypress/commands/fill/pickCheckPickerOptions.ts, src/fields/CheckTreePicker/index.tsx, src/fields/shared/StyledRsuitePickerBox.ts, src/formiks/FormikCheckTreePicker.tsx, stories/fields/CheckTreePicker.stories.tsx, stories/formiks/FormikCheckTreePicker.stories.tsx
- MTES-MCT/monitorenv#2152
https://637e01cf5934a2ae881ccc9d-lcmgbxphdx.chromatic.com/
=> fix(components): add custom icon to checktreepicker

src/assets/icons/Offline.svg, src/icons/Offline.tsx, src/icons/index.tsx
Adding a offline icon 
https://637e01cf5934a2ae881ccc9d-mppkrgbbju.chromatic.com/
=> feat(icons): add offline icon

e2e/base/fields/LinkInput.spec.tsx, package.json, src/cypress/commands/fill/index.ts, src/fields/LinkInput.tsx, src/fields/shared/StyledIMaskInput.ts, src/formiks/FormikLinkInput.tsx, stories/fields/LinkInput.stories.tsx, stories/formiks/FormikLinkInput.stories.tsx
https://637e01cf5934a2ae881ccc9d-xvbeqefuhi.chromatic.com/
=> feat(components): create link component with prefix mask

src/fields/shared/StyledRsuitePickerBox.ts
https://637e01cf5934a2ae881ccc9d-blpzhnbcrv.chromatic.com/
=> [Rsuite combobox] add minheight

src/fields/CheckTreePicker/index.tsx
https://637e01cf5934a2ae881ccc9d-cxyakhulic.chromatic.com/
=> fix(components): set option label value width to 100%

src/entities/ControlUnit/types.ts
- MTES-MCT/monitorenv#2292
https://637e01cf5934a2ae881ccc9d-qddbdsleaw.chromatic.com/
=> feat(types): change label for ControlUnitResourceType.PEDESTRIAN

package.json, yarn.lock
https://637e01cf5934a2ae881ccc9d-rokwulhyur.chromatic.com/
=> fix(deps): upgrade cypress peer deps

e2e/base/fields/CheckTreePicker.spec.tsx, src/fields/CheckTreePicker/RsuiteCheckTreePickerBox.ts, src/fields/CheckTreePicker/__tests__/utils.test.ts, src/fields/CheckTreePicker/index.tsx, src/fields/CheckTreePicker/utils.ts, stories/formiks/FormikCheckTreePicker.stories.tsx
https://637e01cf5934a2ae881ccc9d-kmkqfkqkaz.chromatic.com/
=> feat(components): remove checkbox of 1st node of checktreepicker if it got children

e2e/base/fields/CoordinatesInput.spec.tsx, src/fields/CoordinatesInput/DDCoordinatesInput.tsx, src/fields/CoordinatesInput/DMDCoordinatesInput.tsx
- https://github.com/MTES-MCT/monitorfish/issues/4271
- https://github.com/MTES-MCT/monitorfish/issues/4228
https://637e01cf5934a2ae881ccc9d-vpmdspgpja.chromatic.com/
=> fix(fields): add one more numeric to seconds to dmd coordinates input

src/fields/CoordinatesInput/DDCoordinatesInput.tsx
https://637e01cf5934a2ae881ccc9d-etrpjnobsn.chromatic.com/
=> fix(fields): fix dd coordinates input

package.json, yarn.lock
- Resolve #123
- MTES-MCT/monitorenv#123
- MTES-MCT/monitorfish#123
https://637e01cf5934a2ae881ccc9d-dhqtladnuj.chromatic.com/
=> chore(libs): allow react-sentry v9

src/components/Banner/index.tsx
swap padding to internal banner elements to prevent overflowing
https://637e01cf5934a2ae881ccc9d-poyfntmeoa.chromatic.com/
=> [Banner] Fix padding issues

src/fields/shared/StyledRsuiteCalendarBox.ts
https://637e01cf5934a2ae881ccc9d-zwrbnipcae.chromatic.com/
=> fix(fields): fix DateRangePicker when hasSingleCalendar is true

src/fields/Checkbox.tsx, src/fields/MultiCheckbox.tsx, src/fields/MultiRadio.tsx, src/fields/Radio.tsx, src/fields/Toggle/index.tsx, src/fields/shared/types.ts, stories/fields/Checkbox.stories.tsx, stories/fields/Radio.stories.tsx
and can be placed on right or left (per default label is on the right)
https://637e01cf5934a2ae881ccc9d-dafjbtuqvo.chromatic.com/
=> fix(components): checkbox label can be a React.node 

src/assets/stylesheets/rsuite-override.css, src/tables/TableWithSelectableRows/RowCheckbox.tsx
https://637e01cf5934a2ae881ccc9d-glcqhncwet.chromatic.com/
=> fix(global): fix checkbox and dropdown font

e2e/base/fields/CheckTreePicker.spec.tsx, src/fields/CheckTreePicker/index.tsx, stories/fields/CheckTreePicker/WithCustomSearch.stories.tsx
https://637e01cf5934a2ae881ccc9d-rmykojrgai.chromatic.com/
=> feat(fields): set virualized ans searchable props to true by default on CheckTreePicker

src/fields/CheckTreePicker/__tests__/utils.test.ts, src/fields/CheckTreePicker/index.tsx, src/fields/CheckTreePicker/utils.ts, stories/fields/CheckTreePicker/WithCustomSearch.stories.tsx
https://637e01cf5934a2ae881ccc9d-uzpxdawkmo.chromatic.com/
=> fix(fields): fix rsuite error on CheckTreePicker

src/fields/Search.tsx, src/utils/getSelectedOptionFromOptionValue.ts, stories/fields/Search/WithCustomSearch.stories.tsx, stories/fields/Search/WithOptionsAndCustomMenuItem.stories.tsx, stories/fields/Search/WithQuery.stories.tsx
https://637e01cf5934a2ae881ccc9d-mpdkzjcjjh.chromatic.com/
=> fix(fields): fix search component to display value correctly

src/fields/Select.tsx
https://637e01cf5934a2ae881ccc9d-hogjovgnbo.chromatic.com/
=> fix(fields): delete omit "container" prop in Select component

.github/workflows/release.yml
Correctly pull right yarn version in release job
https://637e01cf5934a2ae881ccc9d-lwejtcwfuj.chromatic.com/
=> fix(global): fix release job

.github/workflows/merge_dependabot_pull_request.yml, .github/workflows/merge_release_pull_request.yml
Pour ne plus dépasser les 100k de run sur Cypress...
https://637e01cf5934a2ae881ccc9d-xebvidfejp.chromatic.com/
=> chore: disable auto rebase of branches

src/fields/MultiZoneEditor/index.tsx
https://637e01cf5934a2ae881ccc9d-gkgglsjstk.chromatic.com/
=> fix(components): Ajout d'un titre au bouton modifier de l'éditeur de zones multiples.
